scoreboard players set @s cooldown 20
scoreboard players set @s dev 36
scoreboard players set @s kv 4
scoreboard players set @s triple 18
scoreboard players set @s volt 28
scoreboard players set @s sen 4
scoreboard players set @s long 6
scoreboard players set @s havoc 24
scoreboard players set @s charge 8
scoreboard players set @s lstar 0
scoreboard players set @s mas 4
scoreboard players set @s pk 5
scoreboard players set @s moz 6
scoreboard players set @s eva 8
scoreboard players set @s r301 18
scoreboard players set @s r99 20
scoreboard players set @s re45 16
scoreboard players set @s p2020 14
scoreboard players set @s g7 20
scoreboard players set @s alt 19
scoreboard players set @s r3030 6
scoreboard players set @s car 20
scoreboard players set @s hem 18
scoreboard players set @s pro 20
scoreboard players set @s ram 28
scoreboard players set @s flat 20
scoreboard players set @s wing 6
scoreboard players set @s spit 35