scoreboard objectives add cooldown dummy

scoreboard players remove @s[scores={cooldown=1..}] cooldown 1
title @s[tag=!reload,scores={cooldown=100}] actionbar Cooldown...100
title @s[tag=!reload,scores={cooldown=99}] actionbar Cooldown...99
title @s[tag=!reload,scores={cooldown=98}] actionbar Cooldown...98
title @s[tag=!reload,scores={cooldown=97}] actionbar Cooldown...97
title @s[tag=!reload,scores={cooldown=96}] actionbar Cooldown...96
title @s[tag=!reload,scores={cooldown=95}] actionbar Cooldown...95
title @s[tag=!reload,scores={cooldown=94}] actionbar Cooldown...94
title @s[tag=!reload,scores={cooldown=93}] actionbar Cooldown...93
title @s[tag=!reload,scores={cooldown=92}] actionbar Cooldown...92
title @s[tag=!reload,scores={cooldown=91}] actionbar Cooldown...91
title @s[tag=!reload,scores={cooldown=90}] actionbar Cooldown...90
title @s[tag=!reload,scores={cooldown=89}] actionbar Cooldown...89
title @s[tag=!reload,scores={cooldown=88}] actionbar Cooldown...88
title @s[tag=!reload,scores={cooldown=87}] actionbar Cooldown...87
title @s[tag=!reload,scores={cooldown=86}] actionbar Cooldown...86
title @s[tag=!reload,scores={cooldown=85}] actionbar Cooldown...85
title @s[tag=!reload,scores={cooldown=84}] actionbar Cooldown...84
title @s[tag=!reload,scores={cooldown=83}] actionbar Cooldown...83
title @s[tag=!reload,scores={cooldown=82}] actionbar Cooldown...82
title @s[tag=!reload,scores={cooldown=81}] actionbar Cooldown...81
title @s[tag=!reload,scores={cooldown=80}] actionbar Cooldown...80
title @s[tag=!reload,scores={cooldown=79}] actionbar Cooldown...79
title @s[tag=!reload,scores={cooldown=78}] actionbar Cooldown...78
title @s[tag=!reload,scores={cooldown=77}] actionbar Cooldown...77
title @s[tag=!reload,scores={cooldown=76}] actionbar Cooldown...76
title @s[tag=!reload,scores={cooldown=75}] actionbar Cooldown...75
title @s[tag=!reload,scores={cooldown=74}] actionbar Cooldown...74
title @s[tag=!reload,scores={cooldown=73}] actionbar Cooldown...73
title @s[tag=!reload,scores={cooldown=72}] actionbar Cooldown...72
title @s[tag=!reload,scores={cooldown=71}] actionbar Cooldown...71
title @s[tag=!reload,scores={cooldown=70}] actionbar Cooldown...70
title @s[tag=!reload,scores={cooldown=69}] actionbar Cooldown...69
title @s[tag=!reload,scores={cooldown=68}] actionbar Cooldown...68
title @s[tag=!reload,scores={cooldown=67}] actionbar Cooldown...67
title @s[tag=!reload,scores={cooldown=66}] actionbar Cooldown...66
title @s[tag=!reload,scores={cooldown=65}] actionbar Cooldown...65
title @s[tag=!reload,scores={cooldown=64}] actionbar Cooldown...64
title @s[tag=!reload,scores={cooldown=63}] actionbar Cooldown...63
title @s[tag=!reload,scores={cooldown=62}] actionbar Cooldown...62
title @s[tag=!reload,scores={cooldown=61}] actionbar Cooldown...61
title @s[tag=!reload,scores={cooldown=60}] actionbar Cooldown...60
title @s[tag=!reload,scores={cooldown=59}] actionbar Cooldown...59
title @s[tag=!reload,scores={cooldown=58}] actionbar Cooldown...58
title @s[tag=!reload,scores={cooldown=57}] actionbar Cooldown...57
title @s[tag=!reload,scores={cooldown=56}] actionbar Cooldown...56
title @s[tag=!reload,scores={cooldown=55}] actionbar Cooldown...55
title @s[tag=!reload,scores={cooldown=54}] actionbar Cooldown...54
title @s[tag=!reload,scores={cooldown=53}] actionbar Cooldown...53
title @s[tag=!reload,scores={cooldown=52}] actionbar Cooldown...52
title @s[tag=!reload,scores={cooldown=51}] actionbar Cooldown...51
title @s[tag=!reload,scores={cooldown=50}] actionbar Cooldown...50
title @s[tag=!reload,scores={cooldown=49}] actionbar Cooldown...49
title @s[tag=!reload,scores={cooldown=48}] actionbar Cooldown...48
title @s[tag=!reload,scores={cooldown=47}] actionbar Cooldown...47
title @s[tag=!reload,scores={cooldown=46}] actionbar Cooldown...46
title @s[tag=!reload,scores={cooldown=45}] actionbar Cooldown...45
title @s[tag=!reload,scores={cooldown=44}] actionbar Cooldown...44
title @s[tag=!reload,scores={cooldown=43}] actionbar Cooldown...43
title @s[tag=!reload,scores={cooldown=42}] actionbar Cooldown...42
title @s[tag=!reload,scores={cooldown=41}] actionbar Cooldown...41
title @s[tag=!reload,scores={cooldown=40}] actionbar Cooldown...40
title @s[tag=!reload,scores={cooldown=39}] actionbar Cooldown...39
title @s[tag=!reload,scores={cooldown=38}] actionbar Cooldown...38
title @s[tag=!reload,scores={cooldown=37}] actionbar Cooldown...37
title @s[tag=!reload,scores={cooldown=36}] actionbar Cooldown...36
title @s[tag=!reload,scores={cooldown=35}] actionbar Cooldown...35
title @s[tag=!reload,scores={cooldown=34}] actionbar Cooldown...34
title @s[tag=!reload,scores={cooldown=33}] actionbar Cooldown...33
title @s[tag=!reload,scores={cooldown=32}] actionbar Cooldown...32
title @s[tag=!reload,scores={cooldown=31}] actionbar Cooldown...31
title @s[tag=!reload,scores={cooldown=30}] actionbar Cooldown...30
title @s[tag=!reload,scores={cooldown=29}] actionbar Cooldown...29
title @s[tag=!reload,scores={cooldown=28}] actionbar Cooldown...28
title @s[tag=!reload,scores={cooldown=27}] actionbar Cooldown...27
title @s[tag=!reload,scores={cooldown=26}] actionbar Cooldown...26
title @s[tag=!reload,scores={cooldown=25}] actionbar Cooldown...25
title @s[tag=!reload,scores={cooldown=24}] actionbar Cooldown...24
title @s[tag=!reload,scores={cooldown=23}] actionbar Cooldown...23
title @s[tag=!reload,scores={cooldown=22}] actionbar Cooldown...22
title @s[tag=!reload,scores={cooldown=21}] actionbar Cooldown...21
title @s[tag=!reload,scores={cooldown=20}] actionbar Cooldown...20
title @s[tag=!reload,scores={cooldown=19}] actionbar Cooldown...19
title @s[tag=!reload,scores={cooldown=18}] actionbar Cooldown...18
title @s[tag=!reload,scores={cooldown=17}] actionbar Cooldown...17
title @s[tag=!reload,scores={cooldown=16}] actionbar Cooldown...16
title @s[tag=!reload,scores={cooldown=15}] actionbar Cooldown...15
title @s[tag=!reload,scores={cooldown=14}] actionbar Cooldown...14
title @s[tag=!reload,scores={cooldown=13}] actionbar Cooldown...13
title @s[tag=!reload,scores={cooldown=12}] actionbar Cooldown...12
title @s[tag=!reload,scores={cooldown=11}] actionbar Cooldown...11
title @s[tag=!reload,scores={cooldown=10}] actionbar Cooldown...10
title @s[tag=!reload,scores={cooldown=9}] actionbar Cooldown...9
title @s[tag=!reload,scores={cooldown=8}] actionbar Cooldown...8
title @s[tag=!reload,scores={cooldown=7}] actionbar Cooldown...7
title @s[tag=!reload,scores={cooldown=6}] actionbar Cooldown...6
title @s[tag=!reload,scores={cooldown=5}] actionbar Cooldown...5
title @s[tag=!reload,scores={cooldown=4}] actionbar Cooldown...4
title @s[tag=!reload,scores={cooldown=3}] actionbar Cooldown...3
title @s[tag=!reload,scores={cooldown=2}] actionbar Cooldown...2
title @s[tag=!reload,scores={cooldown=1}] actionbar Cooldown...1