summon fire:seerf ^^^2
summon fire:seerf ^^^4
summon fire:seerf ^^^6
summon fire:seerf ^^^8
summon fire:seerf ^^^10
summon fire:seerf ^^^12
summon fire:seerf ^^^14
summon fire:seerf ^^^16
summon fire:seerf ^^^18
summon fire:seerf ^^^20
summon fire:seerf ^^^22
summon fire:seerf ^^^24
summon fire:seerf ^^^26
summon fire:seerf ^^^28
summon fire:seerf ^^^30
particle zex:seer_particle ^^^2
particle zex:seer_particle ^^^4
particle zex:seer_particle ^^^6
particle zex:seer_particle ^^^8
particle zex:seer_particle ^^^10
particle zex:seer_particle ^^^12
particle zex:seer_particle ^^^14
particle zex:seer_particle ^^^16
particle zex:seer_particle ^^^18
particle zex:seer_particle ^^^20
particle zex:seer_particle ^^^22
particle zex:seer_particle ^^^24
particle zex:seer_particle ^^^26
particle zex:seer_particle ^^^28
particle zex:seer_particle ^^^30