execute at @e[type=fire:dev, tag=!sound] positioned ~~~ run playsound fire.dev @a ~~~
execute at @e[type=fire:kv, tag=!sound] positioned ~~~ run playsound fire.kv @a ~~~
execute at @e[type=fire:triple, tag=!sound,c=1] positioned ~~~ run playsound fire.triple @a ~~~
execute at @e[type=fire:volt, tag=!sound] positioned ~~~ run playsound fire.volt @a ~~~
execute at @e[type=fire:dev, tag=!sound] positioned ~~~ run playsound fire.dev @a ~~~
execute at @e[type=fire:long, tag=!sound] positioned ~~~ run playsound fire.long @a ~~~
execute at @e[type=fire:flat, tag=!sound] positioned ~~~ run playsound fire.flat @a ~~~
execute at @e[type=fire:sen, tag=!sound] positioned ~~~ run playsound fire.sen @a ~~~
execute at @e[type=fire:long, tag=!sound] positioned ~~~ run playsound fire.long @a ~~~
execute at @e[type=fire:havoc, tag=!sound] positioned ~~~ run playsound fire.havoc @a ~~~
execute at @e[type=fire:lstar, tag=!sound] positioned ~~~ run playsound fire.lstar @a ~~~
execute at @e[type=fire:pk, tag=!sound,c=1] positioned ~~~ run playsound fire.pk @a ~~~
execute at @e[type=fire:sen, tag=!sound] positioned ~~~ run playsound fire.sen @a ~~~
execute at @e[type=fire:tsen, tag=!sound] positioned ~~~ run playsound fire.sen @a ~~~
execute at @e[type=fire:moz, tag=!sound,c=1] positioned ~~~ run playsound fire.moz @a ~~~
execute at @e[type=fire:eva, tag=!sound,c=1] positioned ~~~ run playsound fire.eva @a ~~~
execute at @e[type=fire:r301, tag=!sound] positioned ~~~ run playsound fire.r301 @a ~~~
execute at @e[type=fire:tr301, tag=!sound] positioned ~~~ run playsound fire.r301 @a ~~~
execute at @e[type=fire:str301, tag=!sound] positioned ~~~ run playsound fire.r301 @a ~~~
execute at @e[type=fire:r99, tag=!sound] positioned ~~~ run playsound fire.r99 @a ~~~
execute at @e[type=fire:re45, tag=!sound] positioned ~~~ run playsound fire.re45 @a ~~~
execute at @e[type=fire:p2020, tag=!sound] positioned ~~~ run playsound fire.p2020 @a ~~~
execute at @e[type=fire:g7, tag=!sound] positioned ~~~ run playsound fire.g7 @a ~~~
execute at @e[type=fire:alt, tag=!sound] positioned ~~~ run playsound fire.alt @a ~~~
execute at @e[type=fire:r3030, tag=!sound] positioned ~~~ run playsound fire.r3030 @a ~~~
execute at @e[type=fire:car, tag=!sound] positioned ~~~ run playsound fire.car @a ~~~
execute at @e[type=fire:hem, tag=!sound] positioned ~~~ run playsound fire.hem @a ~~~
execute at @e[type=fire:pro, tag=!sound] positioned ~~~ run playsound fire.pro @a ~~~
execute at @e[type=fire:flat, tag=!sound] positioned ~~~ run playsound fire.flat @a ~~~
execute at @e[type=fire:tflat, tag=!sound] positioned ~~~ run playsound fire.flat @a ~~~
execute at @e[type=fire:stflat, tag=!sound] positioned ~~~ run playsound fire.flat @a ~~~
execute at @e[type=fire:wing, tag=!sound] positioned ~~~ run playsound fire.wing @a ~~~
execute at @e[type=fire:spit, tag=!sound] positioned ~~~ run playsound fire.spit @a ~~~
execute at @e[type=fire:sdev, tag=!sound] positioned ~~~ run playsound fire.dev @a ~~~
execute at @e[type=fire:skv, tag=!sound] positioned ~~~ run playsound fire.kv @a ~~~
execute at @e[type=fire:striple, tag=!sound,c=1] positioned ~~~ run playsound fire.triple @a ~~~
execute at @e[type=fire:svolt, tag=!sound] positioned ~~~ run playsound fire.volt @a ~~~
execute at @e[type=fire:sdev, tag=!sound] positioned ~~~ run playsound fire.dev @a ~~~
execute at @e[type=fire:ssen, tag=!sound] positioned ~~~ run playsound fire.sen @a ~~~
execute at @e[type=fire:long, tag=!sound] positioned ~~~ run playsound fire.long @a ~~~
execute at @e[type=fire:slong, tag=!sound] positioned ~~~ run playsound fire.long @a ~~~
execute at @e[type=fire:sflat, tag=!sound] positioned ~~~ run playsound fire.flat @a ~~~
execute at @e[type=fire:ssen, tag=!sound] positioned ~~~ run playsound fire.volt @a ~~~
#execute at @e[type=fire:sbar, tag=!sound] positioned ~~~ run playsound fire.bar @a ~~~
execute at @e[type=fire:shavoc, tag=!sound] positioned ~~~ run playsound fire.havoc @a ~~~
execute at @e[type=fire:slstar, tag=!sound] positioned ~~~ run playsound fire.lstar @a ~~~
execute at @e[type=fire:spk, tag=!sound,c=1] positioned ~~~ run playsound fire.pk @a ~~~
execute at @e[type=fire:smoz, tag=!sound,c=1] positioned ~~~ run playsound fire.moz @a ~~~
execute at @e[type=fire:seva, tag=!sound,c=1] positioned ~~~ run playsound fire.eva @a ~~~
execute at @e[type=fire:sr301, tag=!sound] positioned ~~~ run playsound fire.r301 @a ~~~
execute at @e[type=fire:sr99, tag=!sound] positioned ~~~ run playsound fire.r99 @a ~~~
execute at @e[type=fire:sre45, tag=!sound] positioned ~~~ run playsound fire.re45 @a ~~~
execute at @e[type=fire:sp2020, tag=!sound] positioned ~~~ run playsound fire.p2020 @a ~~~
execute at @e[type=fire:sg7, tag=!sound] positioned ~~~ run playsound fire.g7 @a ~~~
execute at @e[type=fire:salt, tag=!sound] positioned ~~~ run playsound fire.alt @a ~~~
execute at @e[type=fire:sr3030, tag=!sound] positioned ~~~ run playsound fire.r3030 @a ~~~
execute at @e[type=fire:scar, tag=!sound] positioned ~~~ run playsound fire.car @a ~~~
execute at @e[type=fire:shem, tag=!sound] positioned ~~~ run playsound fire.hem @a ~~~
execute at @e[type=fire:spro, tag=!sound] positioned ~~~ run playsound fire.pro @a ~~~
execute at @e[type=fire:ram, tag=!sound] positioned ~~~ run playsound fire.ram @a ~~~
execute at @e[type=fire:sram, tag=!sound] positioned ~~~ run playsound fire.ram @a ~~~
execute at @e[type=fire:stsen, tag=!sound] positioned ~~~ run playsound fire.sen @a ~~~
execute at @e[type=fire:sflat, tag=!sound] positioned ~~~ run playsound fire.flat @a ~~~
execute at @e[type=fire:swing, tag=!sound] positioned ~~~ run playsound fire.wing @a ~~~
execute at @e[type=fire:sspit, tag=!sound] positioned ~~~ run playsound fire.spit @a ~~~

tag @e[family=bullet, tag=!sound] add sound