title @s[tag=!reload,scores={spit=55}] actionbar §cSpitFire§r 55/55
title @s[tag=!reload,scores={spit=54}] actionbar §cSpitFire§r 54/55
title @s[tag=!reload,scores={spit=53}] actionbar §cSpitFire§r 53/55
title @s[tag=!reload,scores={spit=52}] actionbar §cSpitFire§r 52/55
title @s[tag=!reload,scores={spit=51}] actionbar §cSpitFire§r 51/55
title @s[tag=!reload,scores={spit=50}] actionbar §cSpitFire§r 50/55
title @s[tag=!reload,scores={spit=49}] actionbar §cSpitFire§r 49/55
title @s[tag=!reload,scores={spit=48}] actionbar §cSpitFire§r 48/55
title @s[tag=!reload,scores={spit=47}] actionbar §cSpitFire§r 47/55
title @s[tag=!reload,scores={spit=46}] actionbar §cSpitFire§r 46/55
title @s[tag=!reload,scores={spit=45}] actionbar §cSpitFire§r 45/55
title @s[tag=!reload,scores={spit=44}] actionbar §cSpitFire§r 44/55
title @s[tag=!reload,scores={spit=43}] actionbar §cSpitFire§r 43/55
title @s[tag=!reload,scores={spit=42}] actionbar §cSpitFire§r 42/55
title @s[tag=!reload,scores={spit=41}] actionbar §cSpitFire§r 41/55
title @s[tag=!reload,scores={spit=40}] actionbar §cSpitFire§r 40/55
title @s[tag=!reload,scores={spit=39}] actionbar §cSpitFire§r 39/55
title @s[tag=!reload,scores={spit=38}] actionbar §cSpitFire§r 38/55
title @s[tag=!reload,scores={spit=37}] actionbar §cSpitFire§r 37/55
title @s[tag=!reload,scores={spit=36}] actionbar §cSpitFire§r 36/55
title @s[tag=!reload,scores={spit=35}] actionbar §cSpitFire§r 35/55
title @s[tag=!reload,scores={spit=34}] actionbar §cSpitFire§r 34/55
title @s[tag=!reload,scores={spit=33}] actionbar §cSpitFire§r 33/55
title @s[tag=!reload,scores={spit=32}] actionbar §cSpitFire§r 32/55
title @s[tag=!reload,scores={spit=31}] actionbar §cSpitFire§r 31/55
title @s[tag=!reload,scores={spit=30}] actionbar §cSpitFire§r 30/55
title @s[tag=!reload,scores={spit=29}] actionbar §cSpitFire§r 29/55
title @s[tag=!reload,scores={spit=28}] actionbar §cSpitFire§r 28/55
title @s[tag=!reload,scores={spit=27}] actionbar §cSpitFire§r 27/55
title @s[tag=!reload,scores={spit=26}] actionbar §cSpitFire§r 26/55
title @s[tag=!reload,scores={spit=25}] actionbar §cSpitFire§r 25/55
title @s[tag=!reload,scores={spit=24}] actionbar §cSpitFire§r 24/55
title @s[tag=!reload,scores={spit=23}] actionbar §cSpitFire§r 23/55
title @s[tag=!reload,scores={spit=22}] actionbar §cSpitFire§r 22/55
title @s[tag=!reload,scores={spit=21}] actionbar §cSpitFire§r 21/55
title @s[tag=!reload,scores={spit=20}] actionbar §cSpitFire§r 20/55
title @s[tag=!reload,scores={spit=19}] actionbar §cSpitFire§r 19/55
title @s[tag=!reload,scores={spit=18}] actionbar §cSpitFire§r 18/55
title @s[tag=!reload,scores={spit=17}] actionbar §cSpitFire§r §g17/55
title @s[tag=!reload,scores={spit=16}] actionbar §cSpitFire§r §g16/55
title @s[tag=!reload,scores={spit=15}] actionbar §cSpitFire§r §g15/55
title @s[tag=!reload,scores={spit=14}] actionbar §cSpitFire§r §g14/55
title @s[tag=!reload,scores={spit=13}] actionbar §cSpitFire§r §g13/55
title @s[tag=!reload,scores={spit=12}] actionbar §cSpitFire§r §g12/55
title @s[tag=!reload,scores={spit=11}] actionbar §cSpitFire§r §g11/55
title @s[tag=!reload,scores={spit=10}] actionbar §cSpitFire§r §g10/55
title @s[tag=!reload,scores={spit=9}] actionbar §cSpitFire§r §g9/55
title @s[tag=!reload,scores={spit=8}] actionbar §cSpitFire§r §g8/55
title @s[tag=!reload,scores={spit=7}] actionbar §cSpitFire§r §g7/55
title @s[tag=!reload,scores={spit=6}] actionbar §cSpitFire§r §g6/55
title @s[tag=!reload,scores={spit=5}] actionbar §cSpitFire§r §g5/55
title @s[tag=!reload,scores={spit=4}] actionbar §cSpitFire§r §g4/55
title @s[tag=!reload,scores={spit=3}] actionbar §cSpitFire§r §g3/55
title @s[tag=!reload,scores={spit=2}] actionbar §cSpitFire§r §g2/55
title @s[tag=!reload,scores={spit=1}] actionbar §cSpitFire§r §g1/55
title @s[tag=!reload,scores={spit=0}] actionbar §cSpitFire§r §40/55
